import numpy as np
import pandas as pd
import shap
import matplotlib.pyplot as plt
import matplotlib

matplotlib.rcParams["font.family"] = "Arial"


FEATURE_NAMES_7 = [
    "NIHSS score",
    "Hyperlipidemia",
    "Previous stroke",
    "Age",
    "DM",
    "Anticoagulant",
    "Hemoglobin",
]

FEATURE_NAMES_10 = [
    "NIHSS score",
    "Group",
    "Hyperlipidemia",
    "Previous stroke",
    "Age",
    "DM",
    "Anticoagulant",
    "Hemoglobin",
    "SBP Time rate",
    "SBP min",
]


def plot_of_SHAP(
    model,
    X,
    filename: str,
    max_display: int = 7,
    plot_type: str = "violin",
    show: bool = True,
    drop_multi: bool = True,
):
    """
    Create SHAP summary plot (DeepExplainer) and save to svg.

    Parameters
    ----------
    model : tf.keras.Model
        Trained Keras model.
    X : array-like or pd.DataFrame
        Input features (train/valid). Can be numpy array or DataFrame.
    filename : str
        Output path (e.g., "SHAP.svg").
    max_display : int
        Max features to display.
    plot_type : str
        "violin" or "dot" etc. (see shap.summary_plot).
    show : bool
        Whether to show the plot.
    drop_multi : bool
        If True and 'multi' column exists, it will be dropped.

    Returns
    -------
    explainer : shap.DeepExplainer
    shap_values : np.ndarray
    X_used : np.ndarray
    feature_names : list[str]
    """

    # ---- Ensure DataFrame for column handling ----
    X_df = X if isinstance(X, pd.DataFrame) else pd.DataFrame(X)

    if drop_multi and "multi" in X_df.columns:
        X_df = X_df.drop(columns=["multi"])

    n_features = X_df.shape[1]

    # ---- Feature names ----
    if n_features == 7:
        feature_names = FEATURE_NAMES_7
    elif n_features == 10:
        feature_names = FEATURE_NAMES_10
    else:
        # fallback: use DataFrame column names (or autogenerated integers)
        feature_names = [str(c) for c in X_df.columns]

    X_np = X_df.to_numpy(dtype=float)

    # ---- SHAP ----
    explainer = shap.DeepExplainer(model, X_np)
    shap_values = explainer.shap_values(X_np)

    # shap_values: usually list (per output). Binary output often returns list length 1.
    if isinstance(shap_values, list):
        shap_values = shap_values[0]

    shap_values = np.squeeze(shap_values)

    # ---- Plot ----
    plt.figure(figsize=(8, 8))
    shap.summary_plot(
        shap_values,
        X_np,
        feature_names=feature_names,
        plot_type=plot_type,
        max_display=max_display,
        show=False,
    )
    plt.savefig(filename, format="svg", bbox_inches="tight")
    if show:
        plt.show()
    plt.close()

    return explainer, shap_values, X_np, feature_names
